/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Martin Trafas (https://sketchfab.com/Bexxie)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chevrolet-corvette-c7-2b509d1bce104224b147c81757f6f43a
title: Chevrolet Corvette (C7)
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
// import { useFrame, useLoader } from '@react-three/fiber';
// import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
// import SceneGLTF from './assets/models/car/scene.gltf';

export function CarModel(props) {
  const { nodes, materials } = useGLTF('/src/assets/models/car/car.glb');

  // 輪子不能動 QAQ
  // const gltf = useLoader(GLTFLoader, SceneGLTF);
  // useFrame((state, delta) => {
  //   let t = state.clock.getElapsedTime();
  //   let group = gltf.scene.children[0].children[0].children[0];
  //   group.children[0].rotation.x = t * 2;
  //   group.children[2].rotation.x = t * 2;
  //   group.children[4].rotation.x = t * 2;
  //   group.children[6].rotation.x = t * 2;
  // });

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[160.14, 76.37, 268.66]}
            rotation={[2.2, Math.PI / 2, 0]}
            scale={[100, 100, 101.81]}
          >
            <group rotation={[0, 0, 2.51]} scale={0.4}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Brake_Disc_FL_Brake_Disc_0.geometry}
                material={materials.Brake_Disc}
              />
            </group>
            <group rotation={[Math.PI / 2, 0.94, Math.PI / 2]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Tire_FL_TireMaterial_0.geometry}
                material={materials.TireMaterial}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rim_FL_Rim_0.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rim_FL_Lug_Nuts_0.geometry}
              material={materials.Lug_Nuts}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rim_FL_CorvetteWingEmblem_0.geometry}
              material={materials.CorvetteWingEmblem}
            />
          </group>
          <group
            position={[-159.93, 76.37, 270.74]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={[106.86, 106.86, 108.79]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Brake_Caliper_FL_Brake_Caliper_0.geometry}
              material={materials.Brake_Caliper}
            />
          </group>
          <group
            position={[160.14, 76.37, -270.48]}
            rotation={[2.2, Math.PI / 2, 0]}
            scale={[100, 100, 101.81]}
          >
            <group rotation={[0, 0, 2.51]} scale={0.4}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Brake_Disc_RL_Brake_Disc_0.geometry}
                material={materials.Brake_Disc}
              />
            </group>
            <group rotation={[Math.PI / 2, 0.94, Math.PI / 2]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Tire_RL_TireMaterial_0.geometry}
                material={materials.TireMaterial}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rim_RL_Rim_0.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rim_RL_Lug_Nuts_0.geometry}
              material={materials.Lug_Nuts}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rim_RL_CorvetteWingEmblem_0.geometry}
              material={materials.CorvetteWingEmblem}
            />
          </group>
          <group
            position={[-159.93, 76.37, 270.74]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={[106.86, 106.86, 108.79]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Brake_Caliper_RL_Brake_Caliper_0.geometry}
              material={materials.Brake_Caliper}
            />
          </group>
          <group
            position={[-159.93, 76.37, -270.48]}
            rotation={[-2.2, -Math.PI / 2, 0]}
            scale={[100, 100, 101.81]}
          >
            <group rotation={[0, 0, 2.51]} scale={0.4}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Brake_Disc_RR_Brake_Disc_0.geometry}
                material={materials.Brake_Disc}
              />
            </group>
            <group rotation={[Math.PI / 2, 0.94, Math.PI / 2]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Tire_RR_TireMaterial_0.geometry}
                material={materials.TireMaterial}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rim_RR_Rim_0.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rim_RR_Lug_Nuts_0.geometry}
              material={materials.Lug_Nuts}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rim_RR_CorvetteWingEmblem_0.geometry}
              material={materials.CorvetteWingEmblem}
            />
          </group>
          <group
            position={[-159.93, 76.37, 270.74]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={[106.86, 106.86, 108.79]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Brake_Caliper_RR_Brake_Caliper_0.geometry}
              material={materials.Brake_Caliper}
            />
          </group>
          <group
            position={[-159.93, 76.37, 268.66]}
            rotation={[-2.2, -Math.PI / 2, 0]}
            scale={[100, 100, 101.81]}
          >
            <group rotation={[0, 0, 2.51]} scale={0.4}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Brake_Disc_FR_Brake_Disc_0.geometry}
                material={materials.Brake_Disc}
              />
            </group>
            <group rotation={[Math.PI / 2, 0.94, Math.PI / 2]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Tire_FR_TireMaterial_0.geometry}
                material={materials.TireMaterial}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rim_FR_Rim_0.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rim_FR_Lug_Nuts_0.geometry}
              material={materials.Lug_Nuts}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rim_FR_CorvetteWingEmblem_0.geometry}
              material={materials.CorvetteWingEmblem}
            />
          </group>
          <group
            position={[-159.93, 76.37, 270.74]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={[106.86, 106.86, 108.79]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Brake_Caliper_FR_Brake_Caliper_0.geometry}
              material={materials.Brake_Caliper}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Plastic_0.geometry}
              material={materials.Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Rubber_0.geometry}
              material={materials.Rubber}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_WindowBorder_0.geometry}
              material={materials.WindowBorder}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Chrome_0.geometry}
              material={materials.Chrome}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Shadow_0.geometry}
              material={materials.Shadow}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Mesh_0.geometry}
              material={materials.Mesh}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Side_Mirrors_0.geometry}
              material={materials.Side_Mirrors}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Reflectors_0.geometry}
              material={materials.Reflectors}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Tail_Lights_White_Cover_0.geometry}
              material={materials.Tail_Lights_White_Cover}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Tail_Lights_Red_Cover_0.geometry}
              material={materials.Tail_Lights_Red_Cover}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Daylight_Cover_0.geometry}
              material={materials.Daylight_Cover}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Spoiler_Light_Cover_0.geometry}
              material={materials.Spoiler_Light_Cover}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Main_Headlight_Lens_0.geometry}
              material={materials.Main_Headlight_Lens}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Blinker_Glass_Cover_0.geometry}
              material={materials.Blinker_Glass_Cover}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Tail_Lights_Red_Cover_2_0.geometry}
              material={materials.Tail_Lights_Red_Cover_2}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Side_Reflectors_Cover_0.geometry}
              material={materials.Side_Reflectors_Cover}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Headlight_Cover_0.geometry}
              material={materials.Headlight_Cover}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Exhaust_Housing_0.geometry}
              material={materials.Exhaust_Housing}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Interior_0.geometry}
              material={materials.Interior}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_CorvetteWingEmblem_0.geometry}
              material={materials.CorvetteWingEmblem}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Glossy_Plastic_0.geometry}
              material={materials.Glossy_Plastic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Exhaust_0.geometry}
              material={materials.Exhaust}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Windows_0.geometry}
              material={materials.Windows}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_2_Wipers_0.geometry}
              material={materials.Wipers}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_1_Car_Paint_0.geometry}
              material={materials.Car_Paint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_1_Car_Paint_0_1.geometry}
              material={materials.Car_Paint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_1_Car_Paint_0_2.geometry}
              material={materials.Car_Paint}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_1_Car_Paint_2_0.geometry}
              material={materials.Car_Paint_2}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.CarBody_3_Undercarriage_0.geometry}
              material={materials.Undercarriage}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.License_Plate_LicensePlate_Frame_0.geometry}
              material={materials.LicensePlate_Frame}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.License_Plate_License_Plate_0.geometry}
              material={materials.License_Plate}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/src/assets/models/car/car.glb');
